name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install project dependencies
        working-directory: python/batch 
        run: poetry install

      - name: Static checks 
        working-directory: python/batch 
        run: poetry run ./static_checks.sh 

      - name: Run pytest
        working-directory: python/batch 
        run: poetry run pytest
